[default]
name                     = rootca
domain_suffix            = example.com
aia_url                  = http://$name.$domain_suffix/$name.crt
crl_url                  = http://$name.$domain_suffix/$name.crl
default_ca               = ca_default
name_opt                 = utf8,esc_ctrl,multiline,lname,align

[ca_dn]
commonName               = "Root CA"

[ca_default]
home                     = ./
database                 = $home/db/index
serial                   = $home/db/serial
crlnumber                = $home/db/crlnumber
certificate              = $home/$name.crt
private_key              = $home/private/$name.key
RANDFILE                 = $home/private/random
new_certs_dir            = $home/certs
unique_subject           = no
copy_extensions          = none
default_days             = 3650
default_crl_days         = 365
default_md               = sha256
policy                   = policy_c_o_match

[policy_c_o_match]
countryName              = optional
stateOrProvinceName      = optional
organizationName         = optional
organizationalUnitName   = optional
commonName               = supplied
emailAddress             = optional

[req]
default_bits             = 2048
encrypt_key              = yes
default_md               = sha256
utf8                     = yes
string_mask              = utf8only
prompt                   = no
distinguished_name       = ca_dn

[ca_ext]
basicConstraints         = critical,CA:true
subjectKeyIdentifier     = hash
authorityKeyIdentifier   = keyid:always,issuer
keyUsage                 = critical,keyCertSign,cRLSign

[sub_ca_ext]
basicConstraints         = critical,CA:true,pathlen:0
subjectKeyIdentifier     = hash
authorityKeyIdentifier   = keyid:always,issuer
extendedKeyUsage         = clientAuth,serverAuth
keyUsage                 = critical,keyCertSign,cRLSign

[client_ext]
subjectKeyIdentifier     = hash
authorityKeyIdentifier   = keyid,issuer
basicConstraints         = critical,CA:false
extendedKeyUsage         = clientAuth
keyUsage                 = digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment

[server_ext]
subjectKeyIdentifier     = hash
authorityKeyIdentifier   = keyid,issuer
basicConstraints         = critical,CA:false
extendedKeyUsage         = serverAuth
keyUsage                 = digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment
subjectAltName		 = DNS:localhost
